server:
  port: 8081

spring:

  application:
    name: auth-service

  config:
    import: shared-jwt.yml

  datasource:
    url: jdbc:postgresql://localhost:5432/auction_hub
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop


jwt-processing:
  filter:
    enabled: false

exception-handling:
  enabled: true

logging:
  level:
    com.example.authservice: DEBUG
    com.example.shared.exceptionhandling: DEBUG